---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kuboczoch.
--- DateTime: 28.07.2019 21:04
---

local cfg = {}

cfg.timezone = "Europe/Warsaw" --- http://worldtimeapi.org/api/timezone/

return cfg
