---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kuboczoch.
--- DateTime: 28.07.2019 20:41
---

local internet = require("internet")

local config
if io.open('/etc/datetime_cfg.lua', 'r') then
    config = dofile('/etc/datetime_cfg.lua')
    TIMEZONE = config.timezone
else
    TIMEZONE = "Europe/Warsaw"
end

local datetime = {}

local function split(inputstr, sep)
    if sep == nil then
        sep = "%s"
    end
    local t = {}
    for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
        table.insert(t, str)
    end
    return t
end

local function getDate()
    return split(split(internet.request("http://worldtimeapi.org/api/timezone/" .. TIMEZONE .. ".txt")(), "\n")[3], " ")[2]
end

datetime.getDate = function()
    return split(getDate(), "T")[1]
end

datetime.getTime = function()
    return split(split(getDate(), "T")[2],".")[1]
end

datetime.getDateTime = function()
    return split(split(getDate(), " ")[1],".")[1]
end

return datetime
